"""
Django settings for ADS project.

Generated by 'django-admin startproject' using Django 5.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
from dotenv import load_dotenv
import os
from pathlib import Path
load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False').lower() == 'true'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    'webpush',
    'rest_framework',
    
    'accounts',
    'tickets',
    'company',
    'settings_crm',
    'notifications',
    'asterisk_app',
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'settings_crm.middleware.MaintenanceModeMiddleware',
    'settings_crm.middleware.SecurityHeadersMiddleware',
]

ROOT_URLCONF = 'ADS.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'settings_crm.context_processors.system_settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'ADS.wsgi.application'
# LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'home'
# LOGOUT_REDIRECT_URL = 'login'
AUTH_USER_MODEL = 'accounts.User'
# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': os.getenv('DB_NAME'),
#         'USER': os.getenv('DB_USER'),
#         'PASSWORD': os.getenv('DB_PASSWORD'),
#         'HOST': os.getenv('DB_HOST'),
#         'PORT': os.getenv('DB_PORT'),
#     }
# }

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']  # Убедитесь, что путь верный
# STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# Настройки для загрузки файлов
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Логирование
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
        'audit': {
            'format': '{asctime} -  {levelname} - {module} - {message}',
            'style': '{',
        },
        'notification': {
            'format': '{asctime} - {levelname} - {module} - {message}',
            'style': '{',
        },
    },
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
        'user_context': {
            '()': 'core.logging_filters.UserContextFilter',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'filters': ['require_debug_true'],
            'class': 'logging.StreamHandler',
            'formatter': 'simple'
        },
        'file_general': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs/general.log',
            'maxBytes': 1024*1024*5,  # 5 MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'file_errors': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs/errors.log',
            'maxBytes': 1024*1024*5,  # 5 MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'file_audit': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs/audit.log',
            'maxBytes': 1024*1024*5,  # 5 MB
            'backupCount': 5,
            'formatter': 'audit',
        },
        'file_notifications': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs/notifications.log',
            'maxBytes': 1024*1024*5,  # 5 MB
            'backupCount': 5,
            'formatter': 'notification',
        },
        'mail_admins': {
            'level': 'ERROR',
            'filters': ['require_debug_false'],
            'class': 'django.utils.log.AdminEmailHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file_general', 'file_errors'],
            'level': 'INFO',
            'propagate': True,
        },
        'django.request': {
            'handlers': ['file_errors', 'mail_admins'],
            'level': 'ERROR',
            'propagate': False,
        },
        'django.security': {
            'handlers': ['file_errors', 'mail_admins'],
            'level': 'ERROR',
            'propagate': False,
        },
        'audit': {
            'handlers': ['file_audit'],
            'level': 'INFO',
            'propagate': False,
        },
        'notifications': {
            'handlers': ['file_notifications', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'tickets': {
            'handlers': ['file_general', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'accounts': {
            'handlers': ['file_general', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
}

# Исключаемые из логирования пути
LOGGING_EXCLUDE_PATHS = [
    '/health/',
    '/favicon.ico',
]

# Настройки системы
try:
    from settings_crm.models import SystemSettings
    SYSTEM_SETTINGS = SystemSettings.get_settings()
except:
    SYSTEM_SETTINGS = None
    
# Сигналы
if not os.environ.get('RUN_MAIN', None) == 'true':  # Чтобы не дублировать в dev-сервере
    default_app_config = 'settings_crm.apps.SettingsConfig'
    
    


# Настройки WebPush 
WEBPUSH_SETTINGS = {
    "VAPID_PUBLIC_KEY": os.getenv('VAPID_PUBLIC_KEY'),
    "VAPID_PRIVATE_KEY": os.getenv('VAPID_PRIVATE_KEY'),
    "VAPID_ADMIN_EMAIL": os.getenv('VAPID_ADMIN_EMAIL')
}

# Настройки уведомлений
NOTIFICATION_TYPES = {
    'TICKET_CREATED': {
        'title': 'Новая заявка',
        'options': {
            'body': 'Вам назначена новая заявка #{id}',
            'icon': '/static/images/notification-icon.png',
            'badge': '/static/images/notification-badge.png',
            'vibrate': [200, 100, 200],
        }
    },
    'TICKET_UPDATED': {
        'title': 'Обновление заявки',
        'options': {
            'body': 'Заявка #{id} была обновлена',
            'icon': '/static/images/notification-icon.png',
            'badge': '/static/images/notification-badge.png',
        }
    },
    'TICKET_COMPLETED': {
        'title': 'Заявка выполнена',
        'options': {
            'body': 'Заявка #{id} выполнена',
            'icon': '/static/images/notification-icon.png',
            'badge': '/static/images/notification-badge.png',
        }
    },
    'TICKET_ASSIGNED': {
        'title': 'Назначение заявки',
        'options': {
            'body': 'Вам назначена заявка #{id}',
            'icon': '/static/images/notification-icon.png',
            'badge': '/static/images/notification-badge.png',
        }
    },
}

SMS_NOTIFICATION_TYPES = [
    'TICKET_CREATED',
    'TICKET_ASSIGNED',
    'TICKET_COMPLETED'
]

PUSH_NOTIFICATION_TYPES = ['TICKET_CREATED', 'TICKET_UPDATED', 'TICKET_COMPLETED', 'TICKET_ASSIGNED']

TELE2_API_URL = os.getenv('TELE2_API_URL')
TELE2_API_LOGIN = os.getenv('TELE2_API_LOGIN')
TELE2_API_PASSWORD = os.getenv('TELE2_API_PASSWORD')
TELE2_SENDER = os.getenv('TELE2_SENDER') 

SMS_TEMPLATES = {
    'master': (
        "Новая заявка #{id}\n"
        "Адрес: {address}\n"
        "Исполнитель: {executor}\n"
        "Ссылка: {url}"
    ),
    'worker': (
        "Вам назначена заявка #{id}\n"
        "Адрес: {address}\n"
        "Тип: {specialization}\n"
        "Приоритет: {priority}\n"
        "Ссылка: {url}"
    ),
    'resident': (
        "Ваша заявка #{id} принята\n"
        "Статус: {status}\n"
        "Исполнитель: {executor}\n"
        "Спасибо за обращение!"
    )
}


# Настройки интеграции с Asterisk
ASTERISK_SERVER = os.getenv('ASTERISK_SERVER')
ASTERISK_USER = os.getenv('ASTERISK_USER')
ASTERISK_PASSWORD = os.getenv('ASTERISK_PASSWORD')
ASTERISK_WEBHOOK_SECRET = os.getenv('ASTERISK_WEBHOOK_SECRET')  # Для аутентификации запросов
ALLOWED_ASTERISK_IPS = os.getenv('ALLOWED_ASTERISK_IPS', '').split(',')

# Папки для хранения записей
CALL_RECORDINGS_DIR = os.path.join(MEDIA_ROOT, 'call_recordings')

# Создаем папку для записей, если ее нет
if not os.path.exists(CALL_RECORDINGS_DIR):
    os.makedirs(CALL_RECORDINGS_DIR)
    
# CRM настройки
CRM_BASE_URL = os.getenv('CRM_BASE_URL')
CRM_API_URL = f'{CRM_BASE_URL}/api/v1'
CRM_API_TOKEN = os.getenv('CRM_API_TOKEN')
MISSED_CALLS_NOTIFICATION_EMAIL = os.getenv('MISSED_CALLS_NOTIFICATION_EMAIL')



# Другие настройки
LOGIN_ATTEMPTS_LIMIT = int(os.getenv('LOGIN_ATTEMPTS_LIMIT', 5))
LOGIN_BLOCK_TIME_MINUTES = int(os.getenv('LOGIN_BLOCK_TIME_MINUTES', 15))
MISSED_CALLS_CHECK_INTERVAL = int(os.getenv('MISSED_CALLS_CHECK_INTERVAL', 5))
SMS_NOTIFICATIONS_ENABLED = os.getenv('SMS_NOTIFICATIONS_ENABLED', 'True').lower() == 'true'

# CELERY_TASK_ALWAYS_EAGER = True  # Выполнять задачи сразу, без брокера
# CELERY_TASK_EAGER_PROPAGATES = True
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', 'redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

TESTING = False

# Настройки безопасности
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
X_FRAME_OPTIONS = 'DENY'


# Asterisk настройки
ASTERISK_AMI_HOST = os.getenv('ASTERISK_AMI_HOST', 'localhost')
ASTERISK_AMI_PORT = int(os.getenv('ASTERISK_AMI_PORT', 5038))
ASTERISK_AMI_USER = os.getenv('ASTERISK_AMI_USER', 'crm')
ASTERISK_AMI_PASSWORD = os.getenv('ASTERISK_AMI_PASSWORD', 'your_strong_password')

# UNIX Socket путь
ASTERISK_SOCKET_PATH = os.getenv('ASTERISK_SOCKET_PATH', '/tmp/asterisk_crm.sock')

# Записи звонков
ASTERISK_RECORDINGS_PATH = os.getenv('ASTERISK_RECORDINGS_PATH', '/var/spool/asterisk/monitor')
ASTERISK_RECORDINGS_URL = os.getenv('ASTERISK_RECORDINGS_URL', '/recordings/')