[loggers]
keys=root,asterisk

[handlers]
keys=console,file

[formatters]
keys=json

[logger_asterisk]
level=INFO
handlers=console,file
qualname=asterisk
propagate=0

[handler_file]
class=logging.handlers.TimedRotatingFileHandler
formatter=json
args=('logs/asterisk.log', 'midnight', 30)

[formatter_json]
class=pythonjsonlogger.jsonlogger.JsonFormatter
format=%(asctime)s %(levelname)s %(message)s